# Generated by Django 3.2.23 on 2024-01-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='image',
            field=models.ImageField(blank=True, default='default/dabba_express_logo.png', upload_to='mess_plan_images', verbose_name='Plan image'),
        ),
    ]
